/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_TRAINI_TRAINI_PB_H_INCLUDED
#define PB_TRAINI_TRAINI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _traini_Empty {
    char dummy_field;
} traini_Empty;

typedef struct _traini_Timestamp {
    int64_t seconds;
    int32_t nanos;
} traini_Timestamp;

typedef struct _traini_AudioFormat {
    int32_t sample_rate;
    int32_t channels;
    int32_t bit_depth;
    pb_callback_t encoding;
} traini_AudioFormat;

typedef struct _traini_AudioChunk {
    pb_callback_t audio_data;
    bool has_format;
    traini_AudioFormat format;
    int64_t sequence_number;
    bool has_timestamp;
    traini_Timestamp timestamp;
} traini_AudioChunk;

typedef struct _traini_AudioOutput {
    pb_callback_t audio_data;
    int64_t sequence_number;
} traini_AudioOutput;

typedef struct _traini_AudioComplete {
    int64_t total_chunks;
} traini_AudioComplete;

typedef struct _traini_ErrorEvent {
    pb_callback_t code;
    pb_callback_t message;
} traini_ErrorEvent;

typedef struct _traini_ConversationEvent {
    pb_size_t which_event;
    union {
        traini_AudioOutput audio_output;
        traini_AudioComplete audio_complete;
        traini_ErrorEvent error;
    } event;
} traini_ConversationEvent;

typedef struct _traini_EndConversationRequest {
    pb_callback_t session_id;
} traini_EndConversationRequest;

typedef struct _traini_SessionSummary {
    pb_callback_t session_id;
} traini_SessionSummary;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define traini_Empty_init_default                {0}
#define traini_Timestamp_init_default            {0, 0}
#define traini_AudioChunk_init_default           {{{NULL}, NULL}, false, traini_AudioFormat_init_default, 0, false, traini_Timestamp_init_default}
#define traini_AudioFormat_init_default          {0, 0, 0, {{NULL}, NULL}}
#define traini_ConversationEvent_init_default    {0, {traini_AudioOutput_init_default}}
#define traini_AudioOutput_init_default          {{{NULL}, NULL}, 0}
#define traini_AudioComplete_init_default        {0}
#define traini_ErrorEvent_init_default           {{{NULL}, NULL}, {{NULL}, NULL}}
#define traini_EndConversationRequest_init_default {{{NULL}, NULL}}
#define traini_SessionSummary_init_default       {{{NULL}, NULL}}
#define traini_Empty_init_zero                   {0}
#define traini_Timestamp_init_zero               {0, 0}
#define traini_AudioChunk_init_zero              {{{NULL}, NULL}, false, traini_AudioFormat_init_zero, 0, false, traini_Timestamp_init_zero}
#define traini_AudioFormat_init_zero             {0, 0, 0, {{NULL}, NULL}}
#define traini_ConversationEvent_init_zero       {0, {traini_AudioOutput_init_zero}}
#define traini_AudioOutput_init_zero             {{{NULL}, NULL}, 0}
#define traini_AudioComplete_init_zero           {0}
#define traini_ErrorEvent_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}}
#define traini_EndConversationRequest_init_zero  {{{NULL}, NULL}}
#define traini_SessionSummary_init_zero          {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define traini_Timestamp_seconds_tag             1
#define traini_Timestamp_nanos_tag               2
#define traini_AudioFormat_sample_rate_tag       1
#define traini_AudioFormat_channels_tag          2
#define traini_AudioFormat_bit_depth_tag         3
#define traini_AudioFormat_encoding_tag          4
#define traini_AudioChunk_audio_data_tag         1
#define traini_AudioChunk_format_tag             2
#define traini_AudioChunk_sequence_number_tag    3
#define traini_AudioChunk_timestamp_tag          4
#define traini_AudioOutput_audio_data_tag        1
#define traini_AudioOutput_sequence_number_tag   2
#define traini_AudioComplete_total_chunks_tag    1
#define traini_ErrorEvent_code_tag               1
#define traini_ErrorEvent_message_tag            2
#define traini_ConversationEvent_audio_output_tag 1
#define traini_ConversationEvent_audio_complete_tag 2
#define traini_ConversationEvent_error_tag       100
#define traini_EndConversationRequest_session_id_tag 1
#define traini_SessionSummary_session_id_tag     1

/* Struct field encoding specification for nanopb */
#define traini_Empty_FIELDLIST(X, a) \

#define traini_Empty_CALLBACK NULL
#define traini_Empty_DEFAULT NULL

#define traini_Timestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds,           1) \
X(a, STATIC,   SINGULAR, INT32,    nanos,             2)
#define traini_Timestamp_CALLBACK NULL
#define traini_Timestamp_DEFAULT NULL

#define traini_AudioChunk_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    audio_data,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  format,            2) \
X(a, STATIC,   SINGULAR, INT64,    sequence_number,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         4)
#define traini_AudioChunk_CALLBACK pb_default_field_callback
#define traini_AudioChunk_DEFAULT NULL
#define traini_AudioChunk_format_MSGTYPE traini_AudioFormat
#define traini_AudioChunk_timestamp_MSGTYPE traini_Timestamp

#define traini_AudioFormat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    sample_rate,       1) \
X(a, STATIC,   SINGULAR, INT32,    channels,          2) \
X(a, STATIC,   SINGULAR, INT32,    bit_depth,         3) \
X(a, CALLBACK, SINGULAR, STRING,   encoding,          4)
#define traini_AudioFormat_CALLBACK pb_default_field_callback
#define traini_AudioFormat_DEFAULT NULL

#define traini_ConversationEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,audio_output,event.audio_output),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,audio_complete,event.audio_complete),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,error,event.error), 100)
#define traini_ConversationEvent_CALLBACK NULL
#define traini_ConversationEvent_DEFAULT NULL
#define traini_ConversationEvent_event_audio_output_MSGTYPE traini_AudioOutput
#define traini_ConversationEvent_event_audio_complete_MSGTYPE traini_AudioComplete
#define traini_ConversationEvent_event_error_MSGTYPE traini_ErrorEvent

#define traini_AudioOutput_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    audio_data,        1) \
X(a, STATIC,   SINGULAR, INT64,    sequence_number,   2)
#define traini_AudioOutput_CALLBACK pb_default_field_callback
#define traini_AudioOutput_DEFAULT NULL

#define traini_AudioComplete_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    total_chunks,      1)
#define traini_AudioComplete_CALLBACK NULL
#define traini_AudioComplete_DEFAULT NULL

#define traini_ErrorEvent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   code,              1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define traini_ErrorEvent_CALLBACK pb_default_field_callback
#define traini_ErrorEvent_DEFAULT NULL

#define traini_EndConversationRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1)
#define traini_EndConversationRequest_CALLBACK pb_default_field_callback
#define traini_EndConversationRequest_DEFAULT NULL

#define traini_SessionSummary_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1)
#define traini_SessionSummary_CALLBACK pb_default_field_callback
#define traini_SessionSummary_DEFAULT NULL

extern const pb_msgdesc_t traini_Empty_msg;
extern const pb_msgdesc_t traini_Timestamp_msg;
extern const pb_msgdesc_t traini_AudioChunk_msg;
extern const pb_msgdesc_t traini_AudioFormat_msg;
extern const pb_msgdesc_t traini_ConversationEvent_msg;
extern const pb_msgdesc_t traini_AudioOutput_msg;
extern const pb_msgdesc_t traini_AudioComplete_msg;
extern const pb_msgdesc_t traini_ErrorEvent_msg;
extern const pb_msgdesc_t traini_EndConversationRequest_msg;
extern const pb_msgdesc_t traini_SessionSummary_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define traini_Empty_fields &traini_Empty_msg
#define traini_Timestamp_fields &traini_Timestamp_msg
#define traini_AudioChunk_fields &traini_AudioChunk_msg
#define traini_AudioFormat_fields &traini_AudioFormat_msg
#define traini_ConversationEvent_fields &traini_ConversationEvent_msg
#define traini_AudioOutput_fields &traini_AudioOutput_msg
#define traini_AudioComplete_fields &traini_AudioComplete_msg
#define traini_ErrorEvent_fields &traini_ErrorEvent_msg
#define traini_EndConversationRequest_fields &traini_EndConversationRequest_msg
#define traini_SessionSummary_fields &traini_SessionSummary_msg

/* Maximum encoded size of messages (where known) */
/* traini_AudioChunk_size depends on runtime parameters */
/* traini_AudioFormat_size depends on runtime parameters */
/* traini_ConversationEvent_size depends on runtime parameters */
/* traini_AudioOutput_size depends on runtime parameters */
/* traini_ErrorEvent_size depends on runtime parameters */
/* traini_EndConversationRequest_size depends on runtime parameters */
/* traini_SessionSummary_size depends on runtime parameters */
#define TRAINI_TRAINI_PB_H_MAX_SIZE              traini_Timestamp_size
#define traini_AudioComplete_size                11
#define traini_Empty_size                        0
#define traini_Timestamp_size                    22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
