/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "traini.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(traini_Empty, traini_Empty, AUTO)


PB_BIND(traini_Timestamp, traini_Timestamp, AUTO)


PB_BIND(traini_AudioChunk, traini_AudioChunk, AUTO)


PB_BIND(traini_AudioFormat, traini_AudioFormat, AUTO)


PB_BIND(traini_ConversationEvent, traini_ConversationEvent, 2)


PB_BIND(traini_AudioOutput, traini_AudioOutput, AUTO)


PB_BIND(traini_AudioComplete, traini_AudioComplete, AUTO)


PB_BIND(traini_ErrorEvent, traini_ErrorEvent, AUTO)


PB_BIND(traini_EndConversationRequest, traini_EndConversationRequest, AUTO)


PB_BIND(traini_SessionSummary, traini_SessionSummary, AUTO)



